### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by SL-Y** [huhx0015/HXAudioPlayer#9]
How to play a set of audio?
List<Integer> i = new ArrayList<Integer>();
                i.add(R.raw.sfx_1_sci_fi_5);
                i.add(R.raw.sfx_3_digital_life_1);
                HXSound.load(i,DemoActivity.this);
                HXSound.sound()
                               .play(DemoActivity.this);

**Comment by huhx0015** [comment]
Hi @SL-Y,

Sorry to get back to you late. To play a sound effect from a list, you could do something like this:

```
List<Integer> i = new ArrayList<>();
i.add(R.raw.sfx_1_sci_fi_5);
i.add(R.raw.sfx_3_digital_life_1);

HXSound.sound()
       .load(i.get(0)   
       .play(this); 

HXSound.sound()
       .load(i.get(1)   
       .play(this); 
```
